### PR TITLE
A class name is not required for aggregates.

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by awead** [comment]
@jcoyne I had to rebase this one. Please check my math :smile: and I'll merge.

**Comment by awead** [comment]
grr. I think I bolloxed it.

**Comment by jcoyne** [comment]
@awead Where'd my test go?

**Comment by jcoyne** [comment]
Gah! this was like the impossible rebase.

**Comment by jcoyne** [comment]
Okay, ready to merge.

**Pull request merged**
